#PBS -N masked_mouse
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=32
#PBS -l mem=30G

source /public/home/nieyg/.bash_profile
cd /md01/nieyg/project/lineage_tracing/scATAC/

cellranger-atac count --id=AR3_C4_scATAC \
                        --reference=/md01/nieyg/ref/hard-mask/mm10_hard_masked \
                        --fastqs=/md01/nieyg/project/lineage_tracing/scATAC/rawdata/AR3_C4 \
                        --sample=AR3_C4 \
                        --localcores=32 \
                        --localmem=64

#PBS -N masked_mouse
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=32
#PBS -l mem=30G
source /public/home/nieyg/.bash_profile
cd /md01/nieyg/project/lineage_tracing/scATAC/
cellranger-atac count --id=AR3_C5_scATAC \
                        --reference=/md01/nieyg/ref/hard-mask/mm10_hard_masked \
                        --fastqs=/md01/nieyg/project/lineage_tracing/scATAC/rawdata/AR3_C5 \
                        --sample=AR3_C5 \
                        --localcores=32 \
                        --localmem=64


# mgatk 
## PBS configure 
#PBS -N mgatk_C4
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=16
#PBS -l mem=32G

source /public/home/nieyg/.bash_profile
cd /md01/nieyg/project/lineage_tracing/scATAC/AR3_C4_scATAC/mgatk
source /md01/nieyg/ori/biosoft/conda/etc/profile.d/conda.sh
conda activate r4-base
source /md01/nieyg/software/venv3/bin/activate
mgatk tenx -i /md01/nieyg/project/lineage_tracing/scATAC/AR3_C4_scATAC/outs/possorted_bam.bam \
-o /md01/nieyg/project/lineage_tracing/scATAC/AR3_C4_scATAC/mgatk \
-n AR3_C4_scATAC -g /md01/nieyg/ref/hard-mask/genome_modify/assembly_hardmask_chrM.fasta \
-c 16 -bt CB -b /md01/nieyg/project/lineage_tracing/scATAC/AR3_C4_scATAC/outs/filtered_peak_bc_matrix/barcodes.tsv 

## PBS configure 
#PBS -N mgatk_C5
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=16
#PBS -l mem=32G

source /public/home/nieyg/.bash_profile
cd /md01/nieyg/project/lineage_tracing/scATAC/AR3_C5_scATAC/mgatk
source /md01/nieyg/ori/biosoft/conda/etc/profile.d/conda.sh
conda activate r4-base
source /md01/nieyg/software/venv3/bin/activate
mgatk tenx -i /md01/nieyg/project/lineage_tracing/scATAC/AR3_C5_scATAC/outs/possorted_bam.bam \
-o /md01/nieyg/project/lineage_tracing/scATAC/AR3_C5_scATAC/mgatk \
-n AR3_C5_scATAC -g /md01/nieyg/ref/hard-mask/genome_modify/assembly_hardmask_chrM.fasta \
-c 16 -bt CB -b /md01/nieyg/project/lineage_tracing/scATAC/AR3_C5_scATAC/outs/filtered_peak_bc_matrix/barcodes.tsv 






## PBS configure 
#PBS -N mgatk_C4
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=16
#PBS -l mem=32G

source /public/home/nieyg/.bash_profile
cd /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C4_scATAC/mgatk_for_filtered_cells

source /md01/nieyg/ori/biosoft/conda/etc/profile.d/conda.sh
conda activate r4-base
source /md01/nieyg/software/venv3/bin/activate
mgatk tenx -i /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C4_scATAC/outs/possorted_bam.bam \
-o /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C4_scATAC/mgatk_for_filtered_cells \
-n AR3_C4_scATAC -g /md01/nieyg/ref/hard-mask/genome_modify/assembly_hardmask_chrM.fasta \
-c 16 -bt CB -b /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C4_scATAC/mgatk_for_filtered_cells/barcode.tsv


## PBS configure 
#PBS -N mgatk_C5
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=16
#PBS -l mem=32G

source /public/home/nieyg/.bash_profile
cd /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C5_scATAC/mgatk_for_filtered_cells

source /md01/nieyg/ori/biosoft/conda/etc/profile.d/conda.sh
conda activate r4-base
source /md01/nieyg/software/venv3/bin/activate
mgatk tenx -i /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C5_scATAC/outs/possorted_bam.bam \
-o /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C5_scATAC/mgatk_for_filtered_cells \
-n AR3_C5_scATAC -g /md01/nieyg/ref/hard-mask/genome_modify/assembly_hardmask_chrM.fasta \
-c 16 -bt CB -b /md01/nieyg/project/lineage_tracing/heart_regeneration/00_data/AR3_data/scATAC/AR3_C5_scATAC/mgatk_for_filtered_cells/barcode.tsv



